id: 981f251f6ea244d3ba34b1d9fcdcc78a
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_174-The_Inquiry_of_Lokadhara-v2
  language: en-us
  author: ''
  volume: {}
